### ISSUE TITLE
SyntaxError when compiling

### ISSUE THREAD

**Issue by zengxianghang** [leouieda/tesseroids#32]
There is an error when compiling the source. The prompt message is as follows:

scons: Reading SConscript files ...
  File "D:\tesseroids-1.2.1\tesseroids-1.2.1\SConstruct", line 22
    print "Error: unknown mode '%s'" % (mode)
SyntaxError: invalid syntax

Can you tell me how to solve this problem?

**Comment by leouieda** [comment]
Hi @zengxianghang which Python version are you using? You need 2.7 to use the Scons script for Tesseroids.

**Comment by zengxianghang** [comment]
Thank you @leouieda . My python version is 3.8.0.

**Comment by leouieda** [comment]
Yeah, I never got around to upgrading since SCons didn't move to Python 3 until somewhat recently. Can you try with 2.7 and see if it works?

**Comment by zengxianghang** [comment]
When I changed the version of Python from 3 to 2.7, the error disappeared. But, some warnings appeared.  The prompt message is as follows:

scons: Reading SConscript files ...
Replacing year (2020) and version (1.2.1) in version.c...
**** Compiling in default mode...
scons: done reading SConscript files.
scons: Building targets ...
cl /Fosrc\prismggts.obj /c src\prismggts.c /nologo /Isrc\lib
prismggts.c
src\lib\grav_prism_sph.h(1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
src\prismggts.c(87): warning C4113: “void (__cdecl *)()”和“void (__cdecl *)(void)”的参数列表不同
cl /Fosrc\lib\grav_prism_sph.obj /c src\lib\grav_prism_sph.c /nologo /Isrc\lib
grav_prism_sph.c
src\lib\grav_prism_sph.c(1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\src\lib\grav_prism_sph.h(1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\src\lib\grav_prism.h(1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
cl /Fosrc\lib\grav_prism.obj /c src\lib\grav_prism.c /nologo /Isrc\lib
grav_prism.c
src\lib\grav_prism.c(1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\src\lib\grav_prism.h(1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
cl /Fosrc\lib\logger.obj /c src\lib\logger.c /nologo /Isrc\lib
logger.c
cl /Fosrc\lib\version.obj /c src\lib\version.c /nologo /Isrc\lib
version.c
cl /Fosrc\lib\constants.obj /c src\lib\constants.c /nologo /Isrc\lib
constants.c
cl /Fosrc\lib\geometry.obj /c src\lib\geometry.c /nologo /Isrc\lib
geometry.c
cl /Fosrc\lib\parsers.obj /c src\lib\parsers.c /nologo /Isrc\lib
parsers.c
link /nologo /OUT:bin\prismggts.exe src\prismggts.obj src\lib\grav_prism_sph.obj src\lib\grav_prism.obj src\lib\logger.obj src\lib\version.obj src\lib\constants.obj src\lib\geometry.obj src\lib\parsers.obj
cl /Fosrc\prismgs.obj /c src\prismgs.c /nologo /Isrc\lib
prismgs.c
src\lib\grav_prism_sph.h(1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
src\prismgs.c(89): warning C4113: “void (__cdecl *)()”和“void (__cdecl *)(void)”的参数列表不同
link /nologo /OUT:bin\prismgs.exe src\prismgs.obj src\lib\grav_prism_sph.obj src\lib\grav_prism.obj src\lib\logger.obj src\lib\version.obj src\lib\constants.obj src\lib\geometry.obj src\lib\parsers.obj
cl /Fosrc\prismgx.obj /c src\prismgx.c /nologo /Isrc\lib
prismgx.c
src\lib\grav_prism.h(1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
cl /Fosrc\lib\prismg_main.obj /c src\lib\prismg_main.c /nologo /Isrc\lib
prismg_main.c
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\src\lib\grav_prism.h(1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
src\lib\prismg_main.c(90): warning C4113: “void (__cdecl *)()”和“void (__cdecl *)(void)”的参数列表不同
link /nologo /OUT:bin\prismgx.exe src\prismgx.obj src\lib\logger.obj src\lib\version.obj src\lib\constants.obj src\lib\geometry.obj src\lib\parsers.obj src\lib\prismg_main.obj src\lib\grav_prism.obj
cl /Fosrc\prismgxx.obj /c src\prismgxx.c /nologo /Isrc\lib
prismgxx.c
src\lib\grav_prism.h(1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
link /nologo /OUT:bin\prismgxx.exe src\prismgxx.obj src\lib\logger.obj src\lib\version.obj src\lib\constants.obj src\lib\geometry.obj src\lib\parsers.obj src\lib\prismg_main.obj src\lib\grav_prism.obj
cl /Fosrc\prismgxy.obj /c src\prismgxy.c /nologo /Isrc\lib
prismgxy.c
src\lib\grav_prism.h(1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
link /nologo /OUT:bin\prismgxy.exe src\prismgxy.obj src\lib\logger.obj src\lib\version.obj src\lib\constants.obj src\lib\geometry.obj src\lib\parsers.obj src\lib\prismg_main.obj src\lib\grav_prism.obj
cl /Fosrc\prismgxz.obj /c src\prismgxz.c /nologo /Isrc\lib
prismgxz.c
src\lib\grav_prism.h(1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
link /nologo /OUT:bin\prismgxz.exe src\prismgxz.obj src\lib\logger.obj src\lib\version.obj src\lib\constants.obj src\lib\geometry.obj src\lib\parsers.obj src\lib\prismg_main.obj src\lib\grav_prism.obj
cl /Fosrc\prismgy.obj /c src\prismgy.c /nologo /Isrc\lib
prismgy.c
src\lib\grav_prism.h(1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
link /nologo /OUT:bin\prismgy.exe src\prismgy.obj src\lib\logger.obj src\lib\version.obj src\lib\constants.obj src\lib\geometry.obj src\lib\parsers.obj src\lib\prismg_main.obj src\lib\grav_prism.obj
cl /Fosrc\prismgyy.obj /c src\prismgyy.c /nologo /Isrc\lib
prismgyy.c
src\lib\grav_prism.h(1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
link /nologo /OUT:bin\prismgyy.exe src\prismgyy.obj src\lib\logger.obj src\lib\version.obj src\lib\constants.obj src\lib\geometry.obj src\lib\parsers.obj src\lib\prismg_main.obj src\lib\grav_prism.obj
cl /Fosrc\prismgyz.obj /c src\prismgyz.c /nologo /Isrc\lib
prismgyz.c
src\lib\grav_prism.h(1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
link /nologo /OUT:bin\prismgyz.exe src\prismgyz.obj src\lib\logger.obj src\lib\version.obj src\lib\constants.obj src\lib\geometry.obj src\lib\parsers.obj src\lib\prismg_main.obj src\lib\grav_prism.obj
cl /Fosrc\prismgz.obj /c src\prismgz.c /nologo /Isrc\lib
prismgz.c
src\lib\grav_prism.h(1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
link /nologo /OUT:bin\prismgz.exe src\prismgz.obj src\lib\logger.obj src\lib\version.obj src\lib\constants.obj src\lib\geometry.obj src\lib\parsers.obj src\lib\prismg_main.obj src\lib\grav_prism.obj
cl /Fosrc\prismgzz.obj /c src\prismgzz.c /nologo /Isrc\lib
prismgzz.c
src\lib\grav_prism.h(1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
link /nologo /OUT:bin\prismgzz.exe src\prismgzz.obj src\lib\logger.obj src\lib\version.obj src\lib\constants.obj src\lib\geometry.obj src\lib\parsers.obj src\lib\prismg_main.obj src\lib\grav_prism.obj
cl /Fosrc\prismpot.obj /c src\prismpot.c /nologo /Isrc\lib
prismpot.c
src\lib\grav_prism.h(1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
link /nologo /OUT:bin\prismpot.exe src\prismpot.obj src\lib\logger.obj src\lib\version.obj src\lib\constants.obj src\lib\geometry.obj src\lib\parsers.obj src\lib\prismg_main.obj src\lib\grav_prism.obj
cl /Fosrc\prismpots.obj /c src\prismpots.c /nologo /Isrc\lib
prismpots.c
src\lib\grav_prism_sph.h(1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
src\prismpots.c(86): warning C4113: “void (__cdecl *)()”和“void (__cdecl *)(void)”的参数列表不同
link /nologo /OUT:bin\prismpots.exe src\prismpots.obj src\lib\grav_prism_sph.obj src\lib\grav_prism.obj src\lib\logger.obj src\lib\version.obj src\lib\constants.obj src\lib\geometry.obj src\lib\parsers.obj
cl /Fosrc\tess2prism.obj /c src\tess2prism.c /nologo /Isrc\lib
tess2prism.c
src\tess2prism.c(84): warning C4113: “void (__cdecl *)()”和“void (__cdecl *)(void)”的参数列表不同
link /nologo /OUT:bin\tess2prism.exe src\tess2prism.obj src\lib\logger.obj src\lib\version.obj src\lib\constants.obj src\lib\geometry.obj src\lib\parsers.obj
cl /Fosrc\tessdefaults.obj /c src\tessdefaults.c /nologo /Isrc\lib
tessdefaults.c
cl /Fosrc\lib\glq.obj /c src\lib\glq.c /nologo /Isrc\lib
glq.c
link /nologo /OUT:bin\tessdefaults.exe src\tessdefaults.obj src\lib\logger.obj src\lib\version.obj src\lib\constants.obj src\lib\glq.obj src\lib\geometry.obj
cl /Fosrc\tessgrd.obj /c src\tessgrd.c /nologo /Isrc\lib
tessgrd.c
src\tessgrd.c(63): warning C4113: “void (__cdecl *)()”和“void (__cdecl *)(void)”的参数列表不同
link /nologo /OUT:bin\tessgrd.exe src\tessgrd.obj src\lib\logger.obj src\lib\version.obj src\lib\parsers.obj src\lib\constants.obj
cl /Fosrc\tessgx.obj /c src\tessgx.c /nologo /Isrc\lib
tessgx.c
cl /Fosrc\lib\grav_tess.obj /c src\lib\grav_tess.c /nologo /Isrc\lib
grav_tess.c
cl /Fosrc\lib\tessg_main.obj /c src\lib\tessg_main.c /nologo /Isrc\lib
tessg_main.c
link /nologo /OUT:bin\tessgx.exe src\tessgx.obj src\lib\logger.obj src\lib\version.obj src\lib\grav_tess.obj src\lib\glq.obj src\lib\constants.obj src\lib\geometry.obj src\lib\parsers.obj src\lib\tessg_main.obj
cl /Fosrc\tessgxx.obj /c src\tessgxx.c /nologo /Isrc\lib
tessgxx.c
link /nologo /OUT:bin\tessgxx.exe src\tessgxx.obj src\lib\logger.obj src\lib\version.obj src\lib\grav_tess.obj src\lib\glq.obj src\lib\constants.obj src\lib\geometry.obj src\lib\parsers.obj src\lib\tessg_main.obj
cl /Fosrc\tessgxy.obj /c src\tessgxy.c /nologo /Isrc\lib
tessgxy.c
link /nologo /OUT:bin\tessgxy.exe src\tessgxy.obj src\lib\logger.obj src\lib\version.obj src\lib\grav_tess.obj src\lib\glq.obj src\lib\constants.obj src\lib\geometry.obj src\lib\parsers.obj src\lib\tessg_main.obj
cl /Fosrc\tessgxz.obj /c src\tessgxz.c /nologo /Isrc\lib
tessgxz.c
link /nologo /OUT:bin\tessgxz.exe src\tessgxz.obj src\lib\logger.obj src\lib\version.obj src\lib\grav_tess.obj src\lib\glq.obj src\lib\constants.obj src\lib\geometry.obj src\lib\parsers.obj src\lib\tessg_main.obj
cl /Fosrc\tessgy.obj /c src\tessgy.c /nologo /Isrc\lib
tessgy.c
link /nologo /OUT:bin\tessgy.exe src\tessgy.obj src\lib\logger.obj src\lib\version.obj src\lib\grav_tess.obj src\lib\glq.obj src\lib\constants.obj src\lib\geometry.obj src\lib\parsers.obj src\lib\tessg_main.obj
cl /Fosrc\tessgyy.obj /c src\tessgyy.c /nologo /Isrc\lib
tessgyy.c
link /nologo /OUT:bin\tessgyy.exe src\tessgyy.obj src\lib\logger.obj src\lib\version.obj src\lib\grav_tess.obj src\lib\glq.obj src\lib\constants.obj src\lib\geometry.obj src\lib\parsers.obj src\lib\tessg_main.obj
cl /Fosrc\tessgyz.obj /c src\tessgyz.c /nologo /Isrc\lib
tessgyz.c
link /nologo /OUT:bin\tessgyz.exe src\tessgyz.obj src\lib\logger.obj src\lib\version.obj src\lib\grav_tess.obj src\lib\glq.obj src\lib\constants.obj src\lib\geometry.obj src\lib\parsers.obj src\lib\tessg_main.obj
cl /Fosrc\tessgz.obj /c src\tessgz.c /nologo /Isrc\lib
tessgz.c
link /nologo /OUT:bin\tessgz.exe src\tessgz.obj src\lib\logger.obj src\lib\version.obj src\lib\grav_tess.obj src\lib\glq.obj src\lib\constants.obj src\lib\geometry.obj src\lib\parsers.obj src\lib\tessg_main.obj
cl /Fosrc\tessgzz.obj /c src\tessgzz.c /nologo /Isrc\lib
tessgzz.c
link /nologo /OUT:bin\tessgzz.exe src\tessgzz.obj src\lib\logger.obj src\lib\version.obj src\lib\grav_tess.obj src\lib\glq.obj src\lib\constants.obj src\lib\geometry.obj src\lib\parsers.obj src\lib\tessg_main.obj
cl /Fosrc\tesslayers.obj /c src\tesslayers.c /nologo /Isrc\lib
tesslayers.c
src\tesslayers.c(85): warning C4113: “void (__cdecl *)()”和“void (__cdecl *)(void)”的参数列表不同
link /nologo /OUT:bin\tesslayers.exe src\tesslayers.obj src\lib\logger.obj src\lib\version.obj src\lib\parsers.obj src\lib\geometry.obj src\lib\constants.obj
cl /Fosrc\tessmass.obj /c src\tessmass.c /nologo /Isrc\lib
tessmass.c
src\tessmass.c(62): warning C4113: “void (__cdecl *)()”和“void (__cdecl *)(void)”的参数列表不同
link /nologo /OUT:bin\tessmass.exe src\tessmass.obj src\lib\logger.obj src\lib\version.obj src\lib\parsers.obj src\lib\geometry.obj src\lib\constants.obj
cl /Fosrc\tessmodgen.obj /c src\tessmodgen.c /nologo /Isrc\lib
tessmodgen.c
src\tessmodgen.c(85): warning C4113: “void (__cdecl *)()”和“void (__cdecl *)(void)”的参数列表不同
link /nologo /OUT:bin\tessmodgen.exe src\tessmodgen.obj src\lib\logger.obj src\lib\version.obj src\lib\parsers.obj src\lib\geometry.obj src\lib\constants.obj
cl /Fosrc\tesspot.obj /c src\tesspot.c /nologo /Isrc\lib
tesspot.c
link /nologo /OUT:bin\tesspot.exe src\tesspot.obj src\lib\logger.obj src\lib\version.obj src\lib\grav_tess.obj src\lib\glq.obj src\lib\constants.obj src\lib\geometry.obj src\lib\parsers.obj src\lib\tessg_main.obj
cl /Fosrc\lib\grav_sphere.obj /c src\lib\grav_sphere.c /nologo /Isrc\lib
grav_sphere.c
cl /Fotest\test_all.obj /c test\test_all.c /nologo /Isrc\lib
test_all.c
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_glq.c(502): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_glq.c(504): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_glq.c(505): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_glq.c(506): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_glq.c(508): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_glq.c(509): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_glq.c(511): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_geometry.c(275): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_geometry.c(276): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_geometry.c(277): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_geometry.c(278): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_geometry.c(279): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_geometry.c(280): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_geometry.c(282): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_geometry.c(284): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_geometry.c(286): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_geometry.c(287): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_parsers.c(223): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_parsers.c(224): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_parsers.c(225): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_parsers.c(227): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\../src/lib/grav_prism.h(1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_grav_prism.c(829): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_grav_prism.c(831): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_grav_prism.c(833): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_grav_prism.c(835): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_grav_prism.c(837): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_grav_prism.c(839): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_grav_prism.c(841): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_grav_prism.c(843): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_grav_prism.c(845): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_grav_prism.c(847): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_grav_prism.c(849): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_grav_prism.c(851): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_grav_prism.c(853): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_grav_prism.c(855): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_grav_prism.c(857): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_grav_prism.c(859): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_grav_prism.c(861): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_grav_prism.c(863): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_grav_prism.c(865): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_grav_prism.c(867): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_grav_prism.c(869): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_grav_prism.c(871): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_grav_prism.c(873): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_grav_prism.c(875): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_grav_prism.c(877): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_grav_prism.c(879): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_grav_prism.c(881): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_grav_prism.c(883): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_grav_prism.c(885): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\../src/lib/grav_prism_sph.h(1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_grav_prism_sph.c(149): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_grav_prism_sph.c(151): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_grav_prism_sph.c(153): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_grav_prism_sph.c(155): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_grav_prism_sph.c(157): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_grav_tess.c(609): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_grav_tess.c(611): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_grav_tess.c(613): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_grav_tess.c(615): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_grav_tess.c(617): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_grav_tess.c(619): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_grav_tess.c(621): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_grav_tess.c(623): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_grav_tess.c(625): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_grav_tess.c(627): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_grav_tess.c(629): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
C:\Users\zengxianghang\Desktop\tesseroids-1.2.1\tesseroids-1.2.1\test\test_grav_tess.c(630): warning C4113: “char *(__cdecl *)()”和“char *(__cdecl *)(void)”的参数列表不同
link /nologo /OUT:tesstest.exe test\test_all.obj src\lib\constants.obj src\lib\geometry.obj src\lib\glq.obj src\lib\grav_prism.obj src\lib\grav_prism_sph.obj src\lib\grav_sphere.obj src\lib\grav_tess.obj src\lib\logger.obj src\lib\parsers.obj src\lib\prismg_main.obj src\lib\tessg_main.obj src\lib\version.obj
scons: done building targets.

Sorry for the prompt message containing Chinese.

**Comment by leouieda** [comment]
@zengxianghang no problem, it's always nice to see Tesseroids get used around the world :slightly_smiling_face: The warnings don't seem like anything critical. Could you try running some of the examples to check if the outputs look OK?

**Comment by zengxianghang** [comment]
Despite some warnings, the result is correct. Thank you for your help.
