### ISSUE TITLE
calculate error

### ISSUE THREAD

**Issue by zengxianghang** [leouieda/tesseroids#33]
computation points: tessgrd -r-180/180/-90/90 -b361/181 -z100e03
tesseroids model1:
-180 180 -35 15 0000 -30000 100
The gzz is shown as:
![111](https://user-images.githubusercontent.com/62739219/84648239-5279d680-af37-11ea-9fbc-d1a602273b7c.png)
tesseroids model2:
-180 -160 -35 15 0000 -30000 100
-160 -140 -35 15 0000 -30000 100
-140 -120 -35 15 0000 -30000 100
-120 -100 -35 15 0000 -30000 100
-100 -80 -35 15 0000 -30000 100
-80 -60 -35 15 0000 -30000 100
-60 -40 -35 15 0000 -30000 100
-40 -20 -35 15 0000 -30000 100
-20 0 -35 15 0000 -30000 100
0 20 -35 15 0000 -30000 100
20 40 -35 15 0000 -30000 100
40 60 -35 15 0000 -30000 100
60 80 -35 15 0000 -30000 100
80 100 -35 15 0000 -30000 100
100 120 -35 15 0000 -30000 100
120 140 -35 15 0000 -30000 100
140 160 -35 15 0000 -30000 100
160 180 -35 15 0000 -30000 100
The gzz is shown as:
![222](https://user-images.githubusercontent.com/62739219/84648249-56a5f400-af37-11ea-8a10-7a300628e63d.png)

**Comment by leouieda** [comment]
Hi @zengxianghang could you please provide some more context so I can understand what went wrong (what was your goal, what was the expected result, etc)?

**Comment by zengxianghang** [comment]
Sorry, I didn’t make it clear. Model 1 and model 2 are essentially the same, but the calculated gzz is different.

**Comment by leouieda** [comment]
Ah right, I get it now. Well, this is not entirely unexpected. The forward model is approximate and the quality of the result is really dependent on the ratio of tesseroid size and computation grid height. In this case, your model is a latitudinal band, which is huge. So even with our adaptive discretisation, there is a limit to how much the algorithm can reduce the error. With hug tesseroids like this, it’s always best to break them up into smaller pieces.

**Comment by zengxianghang** [comment]
thank you
